name: libsigopt tests
permissions: read-all
run-name: ${{ github.actor }} is testing ${{ github.repository }}@${{ github.ref }}
on:
  push: {}
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite:
          - testaux
          - testcompute
          - testviews
    env:
      OMP_NUM_THREADS: "1"
      OPENBLAS_NUM_THREADS: "1"
      MKL_NUM_THREADS: "1"
      VECLIB_MAXIMUM_THREADS: "1"
      NUMEXPR_NUM_THREADS: "1"
    steps:
      - name: Setup project
        uses: ./.github/actions/python_setup
      - name: Run tests
        run: uv run pytest -rw --durations=5 --junitxml=junit-results.xml test/${{ matrix.test-suite }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/python_setup
      - name: Run ruff
        run: uv run ruff check .
  ty:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/actions/python_setup
      - name: Run ty
        run: uv run ty check .